### ISSUE TITLE
"Unable to inject dll" error

### ISSUE THREAD

**Issue by nicolasDmit** [Z4ee/StarRail-ACE-EMU#1]
After compilation and putting exe and dll files to game directory i'm trying to launch injector and got this error:
[](url)
![error_injector](https://github.com/Z4ee/StarRail-ACE-EMU/assets/9363556/562f7e17-cda3-4cae-9b56-b530319039d0)

game in folder N:\games\Star Rail
exe injector and dll in folder N:\games\Star Rail\Games with sr.exe

![error_injector_2](https://github.com/Z4ee/StarRail-ACE-EMU/assets/9363556/f95ef7d8-96ca-437a-802e-eb11d74f1bb6)
where am i wrong?

**Comment by nicolasDmit** [comment]
game version: 1.4.0

**Comment by Z4ee** [comment]
![image](https://github.com/Z4ee/StarRail-ACE-EMU/assets/113752393/7e70a997-6850-4d5c-92c1-6a0caa7b0200)
