### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by MoonShadowIllusion** [Z4ee/StarRail-ACE-EMU#3]
after startup, the game screen appears and then disappears,can you work properly?

**Comment by Z4ee** [comment]
Without context I can't fix the error
try using x64dbg and explain to me where the crash occurs

send me your `GameAssembly.dll`

**Comment by MoonShadowIllusion** [comment]
its my global server [GameAssembly.dll](https://drive.google.com/file/d/1VayF8Ie3xf8SZ470hOFH0io1t6SjPDNw/view?usp=drive_link) , there may be an error in my compilation method. can you provide your compilation results?

**Comment by Z4ee** [comment]
inject this dll using `sr-injector.exe` and write what it displays in the console

[star-rail-gac.zip](https://github.com/Z4ee/StarRail-ACE-EMU/files/13448466/star-rail-gac.zip)

**Comment by MoonShadowIllusion** [comment]
`13F458, CF64000, D519, 8B0000, 8BBBFB`

**Comment by Z4ee** [comment]
try this

[star-rail-ace.zip](https://github.com/Z4ee/StarRail-ACE-EMU/files/13448646/star-rail-ace.zip)

**Comment by MoonShadowIllusion** [comment]
still the same

**Comment by MoonShadowIllusion** [comment]
you can communicate with me on discord

**Comment by Z4ee** [comment]
> you can communicate with me on discord

send me your discord tag

**Comment by MoonShadowIllusion** [comment]
`keqing.`

**Comment by Z4ee** [comment]
fixed

https://github.com/Z4ee/StarRail-ACE-EMU/commit/2e8a9117b97692d092a01528f16b8a03ef0de639
