### ISSUE TITLE
Dump game 

### ISSUE THREAD

**Issue by tuananhcn** [Z4ee/StarRail-ACE-EMU#5]
Im trying to dump honkai impact 3 to try this bypass. But i cant dump it using il2cpp dumper gave me error. Im stuck, could u help me plz tks

**Comment by Z4ee** [comment]
because in hi3 modified il2cpp structures + they are encrypted

**Comment by pubgseller** [comment]
> 因为在 HI3 中修改了 IL2CPP 结构 + 它们是加密的

sir i can add your discord/tg? I'm looking for a provider to bypass ace, can check my github
